/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

import org.booking.App;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
     
    }
}
